/**
 * Blog article generator — Cloudflare Worker.
 *
 * Accepts a raw blog article (rowDoc), normalizes it into circuit-ready
 * field elements (normDoc), registers the document hash with Lemma, and
 * submits a ZK proof of the article's attributes.
 *
 * Pre-deployed by Lemma for the example-x402 demo. If you follow the
 * example as-is, you do not need to redeploy this worker.
 */

import { Hono } from "hono";
// @ts-expect-error — wasm-pack output has no TS declarations
import init, { normalize as wasmNormalize } from "../../normalize/pkg/normalize.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Env = {
  readonly LEMMA_API_BASE: string;
  readonly LEMMA_API_KEY?: string;
  readonly CIRCUIT_ID: string;
  readonly SCHEMA_ID: string;
  readonly ISSUER_ID?: string;
};

/** Raw blog article (rowDoc). */
type BlogArticle = Readonly<{
  title: string;
  author: string;
  body: string;
  publishedAt: string;
  lang: string;
}>;

/** Normalized article attributes (normDoc output from WASM). */
type NormArticle = Readonly<{
  author: string;
  published: number;
  integrity: string;
  words: number;
  lang: string;
}>;

type GenerateRequest = Readonly<{
  /** Raw blog article. */
  article: BlogArticle;
  /** Subject DID (the author). */
  subjectId: string;
  /** Optional: override issuer DID (defaults to env.ISSUER_ID). */
  issuerId?: string;
  /** Optional: chain ID for cross-chain registration. */
  chainId?: number;
  /**
   * Optional: BBS+ selective disclosure to attach.
   * When omitted, the document is registered without disclosure.
   * In production, the issuer signs and reveals chosen attributes
   * via @lemmaoracle/lemma disclose.sign → disclose.reveal.
   */
  disclosure?: Record<string, unknown>;
}>;

type GenerateResponse = Readonly<{
  docHash: string;
  commitment: string;
  attributes: Readonly<Record<string, unknown>>;
  status: "registered" | "error";
  error?: string;
}>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const lemmaFetch = async (
  env: Env,
  path: string,
  body: unknown,
): Promise<Response> => {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (env.LEMMA_API_KEY) {
    headers["Authorization"] = `Bearer ${env.LEMMA_API_KEY}`;
  }
  return fetch(`${env.LEMMA_API_BASE.replace(/\/$/, "")}${path}`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
};



// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

const app = new Hono<{ Bindings: Env }>();

/**
 * POST /generate
 *
 * Accepts a blog article, normalizes it, registers with Lemma,
 * and submits the attribute proof.
 */
app.post("/generate", async (c) => {
  const req = await c.req.json<GenerateRequest>();

  if (!req.article?.title || !req.article?.author || !req.article?.body) {
    return c.json(
      { error: "article.title, article.author, and article.body are required" },
      400,
    );
  }

  // 1. Initialize WASM and normalize rowDoc → normDoc
  await init();
  const normJson = wasmNormalize(JSON.stringify(req.article));
  const norm: NormArticle = JSON.parse(normJson);
  const issuerId = req.issuerId ?? c.env.ISSUER_ID ?? "did:example:publisher";

  // Derive deterministic doc hash from integrity (SHA-256 of body)
  const docHash = `0x${norm.integrity}`;

  // Public attributes stored in Lemma (queryable, ZK-verified)
  const attributes: Record<string, unknown> = {
    author: norm.author,
    published: norm.published,
    integrity: norm.integrity,
    words: norm.words,
    lang: norm.lang,
  };

  // Circuit inputs (string-encoded field elements)
  const inputs: ReadonlyArray<string> = [
    norm.author,
    String(norm.published),
    norm.integrity,
    String(norm.words),
    norm.lang,
  ];

  // 2. Register document with Lemma
  const regResponse = await lemmaFetch(c.env, "/documents/register", {
    docHash,
    schemaId: c.env.SCHEMA_ID,
    issuerId,
    subjectId: req.subjectId,
    chainId: req.chainId,
    attributes: Object.entries(attributes).map(([name, value]) => ({
      name,
      value,
      type: typeof value,
    })),
  });

  if (!regResponse.ok) {
    const err = await regResponse.text();
    return c.json(
      { docHash, commitment: norm.commitment.toString(), attributes, status: "error" as const, error: `Registration failed: ${err}` },
      regResponse.status as 500,
    );
  }

  // 3. Submit proof with Lemma
  const proofResponse = await lemmaFetch(c.env, "/proofs/submit", {
    docHash,
    circuitId: c.env.CIRCUIT_ID,
    proof: "", // Placeholder — in production, generated by snarkjs.groth16.fullProve
    inputs,
    disclosure: req.disclosure,
  });

  if (!proofResponse.ok) {
    const err = await proofResponse.text();
    return c.json(
      { docHash, commitment: norm.commitment.toString(), attributes, status: "error" as const, error: `Proof submission failed: ${err}` },
      proofResponse.status as 500,
    );
  }

  return c.json({
    docHash,
    commitment: norm.commitment.toString(),
    attributes,
    status: "registered" as const,
  } satisfies GenerateResponse);
});

// Health check
app.get("/", (c) =>
  c.json({ status: "ok", service: "lemma-generator", circuit: c.env.CIRCUIT_ID }),
);

export default app;
